version: '3.4'

services:
  mongodb:
    image: "${IMG_MONGODB}"
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    ports:
      - "${MONGODB_EXPOSE}:${MONGODB_EXPOSE}"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 64M

  user:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      APP_PORT: "${APP_PORT}"
      DB_USER: "${MONGO_INITDB_ROOT_USERNAME}"
      DB_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
      DB_HOST: "mongodb"
      DB_PORT: "${MONGODB_EXPOSE}"
      DB_NAME: "${DB_NAME}"
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - mongodb
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 64M
